### ISSUE TITLE
datargs doesn't seem to support `from __future__ import annotations`

### ISSUE THREAD

**Issue by rggjan** [roee30/datargs#10]
It will crash in `if issubclass(dispatch_type, typ):`...

**Comment by roee30** [comment]
You are correct. The only solution I can think of is extracting the globals and locals from the stack, but it defeats the purpose of string annotations. So, I don't think there's a proper solution, but I'm open to suggestions.

**Comment by rggjan** [comment]
Given that this is scheduled to be the default behaviour in [python 3.10](https://www.python.org/dev/peps/pep-0563/#id11) or [python 3.11](https://bugs.python.org/issue38605), would this make `datargs` obsolete / unusable at that point, if no solution is found?

For suggestions: Looking at https://www.python.org/dev/peps/pep-0563/#resolving-type-hints-at-runtime it seems the way to go would be to use `typing.get_type_hints(obj, globalns=None, localns=None)` or `eval()`?

**Comment by rggjan** [comment]
Hmm... actually, if [PEP 649](https://www.python.org/dev/peps/pep-0649/) is accepted, the current method might keep working. Still, would be nice to support the `from __future__` if possible until that happens...

**Comment by roee30** [comment]
Closed until further developments with PEP 649
