### ISSUE TITLE
Slight error in comparison to simple-parsing

### ISSUE THREAD

**Issue by rggjan** [roee30/datargs#13]
Comaring to simple-parsing, the README says:
```
Use datargs if you:
- prefer dashes (--like-this) over underscores (--like_this)
```

This is not true (anymore), as simple-parse also supports the dash variants (as an option you can set globally):
https://github.com/lebrice/SimpleParsing/blob/master/simple_parsing/parsing.py#L50

**Comment by roee30** [comment]
Fixed. Thank you for your attention.
