### ISSUE TITLE
feature request: union of arg classes

### ISSUE THREAD

**Issue by yuvval** [roee30/datargs#2]
Let's say we have two data classes, which both are required. E.g. model config and data config. 
Would it be possible to arg-parse a union of both?

**Comment by roee30** [comment]
In type theory, a union represents an "either/or" relationship, but it seems like the scenario you describe requires an "and" relationship. This might be technically possible to acheive using multiple inheritance, but I wouldn't recommend it. It is possible to implement a new class whose fields are copied from both previous classes, and separate them to two different objects after parsing. Finally, you can use [simple parsing](https://pypi.org/project/simple-parsing/), which supports nested parsing, and create a class with two fields, one for each previous class.

**Comment by yuvval** [comment]
Wearing with simple parsing looks great, but it doesn't has attrs support ;)

**Comment by yuvval** [comment]
*nesting (autocorrect)

**Comment by roee30** [comment]
I don't plan to add nesting support. Please let me know if there's anything else that can be done.

**Comment by yuvval** [comment]
No.
Thanks a lot for your quick reply and for the reference about
simple-parsing.
