### ISSUE TITLE
[Feature request] make `aliases` in `arg()` behaves same as in the original `add_argument()` method

### ISSUE THREAD

**Issue by Diogo-Rossi** [roee30/datargs#30]
The first argument of the original [`add_argument()`](https://docs.python.org/3/library/argparse.html#the-add-argument-method) method is the [name or flags](https://docs.python.org/3/library/argparse.html#name-or-flags) positional argument that can be a series of flags.

The function `args()` could accept the same format.

I think this can be achieved with this simple modification:

```diff
 def arg(
+    *aliases: str,
     positional=False,
     nargs=None,
     const=None,
@@ -569,7 +570,6 @@ def arg(
     choices=None,
     help=None,
     metavar=None,
-    aliases: Sequence[str] = (),
     **kwargs,
 ) -> Any:
     """
```

What do you think?

**Comment by roee30** [comment]
I like this for ergonomics. We can introduce this in a new major version (since this is a breaking change). However, I don't have time to implement this

**Comment by Diogo-Rossi** [comment]
I tried to make this on PR #32.
The tests are passing and the parts of the docs were modified.
But I made very small modifications and can't say if all the situations are covered.
But you can let it open as an idea to a future new major version.
