### ISSUE TITLE
[Feature request] Support mutually exclusive parameters

### ISSUE THREAD

**Issue by Diogo-Rossi** [roee30/datargs#31]
As informed in [this section of README.md](https://github.com/roee30/datargs#why-are-mutually-exclusive-options-not-supported), the groups of [mutually exclusive options](https://docs.python.org/3/library/argparse.html#mutual-exclusion) are not supported.
I would like to discuss this feature and some solutions.

One idea to support that would be with an additional argument `mutually_exclusive_groups` in the `argsclass` decorator:

```python
GroupName = str # type alias
GroupRequired = bool # type alias

def argsclass(
    ...
    mutually_exclusive_groups: dict[GroupName, GroupRequired] = None
    ...
):
```
It may also be added to the `arg` function, receiving the name of the group.

Usage:
```python
from datargs import argsclass, arg


@argsclass(mutually_exclusive_groups={"group1": True})
class Args:
    foo: str = arg(mutually_exclusive_group="group1")
    bar: str = arg(mutually_exclusive_group="group1")
```

Is that feasible?

**Comment by roee30** [comment]
Your example `Args` class cannot be instantiated correctly. Its mutually exclusive arg group would have either `foo` or `bar`, but not both. However, the class `Args` has both of these fields. In type theory terms one would say that this class is a product type, while it should really be a sum type. Sum types a represented by `Union` in Python. However, as explained in the readme, the `Union` type is reserved for subcommands.
Originally, this library was meant to save as much `argparse` boilerplate as possible in the most common cases. My prime tendency is not to complicate it unnecessarily. However, if you'd like, you can try implementing something like this for me to consider:
```
from datargs import argsclass, mutually_exclusive_group

@argsclass
class Group1:
    foo: str
    bar: str

@argsclass
class Group2:
    baz: int
    spam: int

@argsclass
class Args:
    group: Union[Group1, Group2] = mutually_exclusive_group(required=True)
```
The implementation should probably be along these lines: `mutually_exclusive_group()` would return a `dataclass.field()` with an appropriate key in its `metadata`, which `_make_parser()` would check for and build the appropriate parser.
Note that an implementation should include appropriate tests and clear error messages for plausible user errors.

**Comment by Diogo-Rossi** [comment]
Thank you for the comment. But I did not understand very well. 

I thought "mutually exclusive group" meant that only one of the arguments of the group can be present on the command line
Like in this example:

```python
>>> parser = argparse.ArgumentParser(prog='PROG')
>>> group = parser.add_mutually_exclusive_group()
>>> group.add_argument('--foo', action='store_true')
>>> group.add_argument('--bar', action='store_false')
>>> parser.parse_args(['--foo'])
Namespace(bar=True, foo=True)
>>> parser.parse_args(['--bar'])
Namespace(bar=False, foo=False)
>>> parser.parse_args(['--foo', '--bar'])
usage: PROG [-h] [--foo | --bar]
PROG: error: argument --bar: not allowed with argument --foo
```

But, in your example, `Group1` could be passed with the 2 arguments `foo` and `bar` without problem. Is that right?

**Comment by Diogo-Rossi** [comment]
In my example, the class `Args` has both of these fields. But (in theory) only one of them could be present in the command line if they are in the mutually exclusive group (and maybe that requires a more complicated implementation)

**Comment by roee30** [comment]
I apologize, I haven't used mutually exclusive arguments in a while, so my example is incorrect. My comment about your suggestion, however, still stands: the class `Args` has both `foo` and `bar` fields, but the program only accepts one of them on the command line. So when instantiating the class when `foo` is passed, what would `bar` hold? It would have to be `None`, which is not a member of `bar`'s type. This could be circumvented by having both `foo` and `bar` be `Optional[str]`, but then an instance when both are `None` is type-correct, and therefore the class does not correctly represent the command line interface.

My suggestion addresses this. However, it would have to be modified so that each class will only include one option from the mutually exclusive group. This means creating a class for each command line option in the group. I think this is not a sufficiently ergonomic solution and I don't see an alternative. There would have to be another suggestion for type-correct mutually exclusive groups.

**Comment by Diogo-Rossi** [comment]
> So when instantiating the class when `foo` is passed, what would `bar` hold? It would have to be `None`

Actually (to reproduce the original behaviour) `bar` would hold it's default value in this situation (when only `foo` is chosen to be passed).

But, you're right: when instantiating the dataclass (at the end of the process) both values would be present. And the parsing process would raise an error when the 2 options is present in the command line. So the problem still stands.

Maybe the `argsclass` decorator could change the way the class is instantiated (when there is a `mutually_exclusive_group` parameter), but we will have to think more about it.

**Comment by Diogo-Rossi** [comment]
Hi @roee30 

I thought a little about this:
>But, you're right: when instantiating the dataclass (at the end of the process) both values would be present. And the parsing process would raise an error when the 2 options is present in the command line. So the problem still stands.

Actually, I think there is no problem in having the 2 fields in the final class instance, because [`argparse` will make sure that only one of the arguments in the mutually exclusive group was present on the **command line**](https://docs.python.org/3/library/argparse.html#mutual-exclusion:~:text=argparse%20will%20make%20sure%20that%20only%20one%20of%20the%20arguments%20in%20the%20mutually%20exclusive%20group%20was%20present%20on%20the%20command%20line%3A), but they both may be present in the class.

Take a look on this example:

```python
import argparse

parser = argparse.ArgumentParser(prog="PROG")
group = parser.add_mutually_exclusive_group()
group.add_argument("--foo")
group.add_argument("--bar")

args = parser.parse_args(['--foo', 'test'])

print(args) 
# Output: Namespace(foo='test', bar=None)
```

The other not passed argument receives the value of its default. And mutually exclusive arguments must be optional.

Is that right?

**Comment by Diogo-Rossi** [comment]
> One of my concerns is that I don't really like naming groups with a string like in your opening comment for this issue since it doesn't detect typos.

Yeah, you're right.
I know that this is not nice but... what about integers?

**Comment by roee30** [comment]
No satisfactory solution was found

**Comment by julien-blanchon** [comment]
I'm doing mutually exclusive parameters by using union disjoinction with `cyclopts`

```python
from dataclasses import dataclass
from typing import Annotated, Literal

import cyclopts
from pydantic import Field

app = cyclopts.App(
    "example",
)


@dataclass
class DatasetImage:
    type: Literal["image"]
    path: str
    resolution: tuple[int, int]


@dataclass
class DatasetVideo:
    type: Literal["video"]
    path: str
    resolution: tuple[int, int]
    fps: int


@dataclass
class Config:
    dataset: Annotated[DatasetImage | DatasetVideo, Field(discriminator="type")]


@app.default
def main(config: Config):
    print(config)


if __name__ == "__main__":
    # import json
    # from dataglasses import from_dict, to_json_schema
    # schema = to_json_schema(Dataset, strict=True)
    # with open(".schema.json", "w") as f:
    #     json.dump(schema, f)

    app()
```
