### ISSUE TITLE
Boolean argument handling

### ISSUE THREAD

**Issue by stadlerb** [roee30/datargs#36]
Hello,

I tried to use argparse for my CLI application, but I can't find any good way of implementing boolean flags.

E.g. consider the following code in a file called `example.py`:
```python
from datargs import argsclass, parse


@argsclass
class Args:
    flag_enabled: bool = True


args = parse(Args)

print(args)
```

Executing the example with the default value will output the following, which is fine:
```
$ python example.py
Args(flag_enabled=True)
```

But how to toggle the flag?
```
$ python example.py --help
usage: example.py [-h] [--flag-enabled]

options:
  -h, --help      show this help message and exit
  --flag-enabled
```

So I have to pass `--flag-enabled` to disable the flag, which is obviously counter-intuitive:
```
$ python example.py --flag-enabled
Args(flag_enabled=False)
```

What I would expect is either having fuzzy-boolean parsing (e.g. `--flag-enabled=False`) or `store_false` with some prefix/suffix added or replaced according to some set of rules (e.g. `--no-flag-enabled` or `--flag-disabled`) or a name to be specified manually.

Of course it is possible to add an alias:
```pythonfrom datargs import arg, argsclass, parse


@argsclass
class Args:
    flag_enabled: bool = arg("--flag-disabled", default=True)


args = parse(Args)

print(args)
```

```
$ python example.py --flag-disabled
Args(flag_enabled=False)
```

But then the `--flag-enabled` argument still remains available and does the same as `--flag-disabled`, since it is only an alias:
```
$ python example.py --help
usage: example.py [-h] [--flag-enabled]

options:
  -h, --help            show this help message and exit
  --flag-enabled, --flag-disabled
```

Is there any way to replace the name instead of adding an alias?

**Comment by roee30** [comment]
The currently supported solution is:

```python
@argsclass
class Args:
    no_feature: bool = False
```

(`= False` is optional)

Then the default is that the feature is enabled, and `--no-feature` disables it.

`store_false` is currently unsupported.
