### ISSUE TITLE
Static/dynamic type consistency for optional parameters, nargs?

### ISSUE THREAD

**Issue by brentyi** [roee30/datargs#4]
Hi!

@roee30 do you have any suggestions for how to make static and dynamic types consistent when using `nargs` or optional parameters with a default value of `None`?

In particular, I'd like to write something like:

```python
import datargs
from typing import List, Optional

@dataclasses.dataclass(frozen=True)
class CliArgs:
    paths: List[str] = datargs.arg(
        positional=True,
        nargs="+",
        help="List of paths.",
    )
    number: Optional[int] = datargs.arg(default=None)

args = datargs.parse(CliArgs)

# args.paths is a list, args.number is `None` or an integer
```

But this doesn't work, and I instead have to write:

```python
import datargs

@dataclasses.dataclass(frozen=True)
class CliArgs:
    paths: str = datargs.arg(
        positional=True,
        nargs="+",
        help="List of paths.",
    )
    number: int = datargs.arg(default=None)

args = datargs.parse(CliArgs)

# Dynamically, args.paths is a list, args.number is `None` or an integer
# But type checkers, IDEs, etc will treat args.path as a string, and args.number as always an integer
```

Thanks!!

**Comment by roee30** [comment]
I just released version `0.5.0` with nargs support, supporting `List` and `Sequence` exactly as you wrote.

`Optional` is not supported yet. Does it create a type-checking issue? If so, how can it be reproduced?

**Comment by brentyi** [comment]
Thanks for making a release!! Just updated and it works great.

Generally it feels a bit unsafe that a variable that's not typed as a `None` or `Optional` might contain a `None` value in it. Here's an example of where `Optional` might be nice:
```python
import datargs

@dataclasses.dataclass(frozen=True)
class CliArgs:
    maybe_number: int = datargs.arg(default=None)

args = datargs.parse(CliArgs)

# Runtime error if `maybe_number` is None, even though according to static type this operation is safe
print("Your number plus 5 is:", args.maybe_number + 5)
```

If it was possible to type `maybe_number` with `Optional[int]`, this kind of error could be flagged by mypy.

**Comment by roee30** [comment]
Version 0.6.0 was released with this fix

**Comment by brentyi** [comment]
That was lightning fast; really appreciate it.
