### ISSUE TITLE
Optional typing with Enum class

### ISSUE THREAD

**Issue by comfortablynick** [roee30/datargs#8]
I am having issues using Enum for an optional parameter. It looks like support for optional typing was added in #4, so it may be the Enum class causing the issue.

```python
class Item(enum.Enum):
    car = 0
    truck = 0


@dataclass
class Args:
    item: typing.Optional[Item] = None
```

Using with optional gives me this error:
```
error: argument --item: invalid Item value: 'car'
```

Trying without `Optional` and a default of `None` _works_, but the type checker doesn't like it:
```
Expression of type "Item | None" cannot be assigned to declared type "Item"
```

**Comment by roee30** [comment]
Thank you for reporting. Fix is released in 0.8.0
